module.exports = {
  property: [
    "marketingTitle",
    "excerpt",
    "listingCard.eyebrow",
    "listingCard.title",
    "listingCard.excerpt",
    "listingCard.ctaLabel",
    "listingCard.statusLabel",
    "heroExcerpt",
    "sidebarBlocks[].eyebrow",
    "sidebarBlocks[].title",
    "sidebarBlocks[].text",
    "sidebarBlocks[].items[]",
    "sidebarBlocks[].caption",
    "sidebarBlocks[].ctaLabel",
    "sidebarBlocks[].image.alt",
    "seo.metaTitle",
    "seo.metaDescription",
    "gallery[].alt",
    "priceAndRisks.priceHeading",
    "priceAndRisks.priceLabel",
    "priceAndRisks.agencyFeesNote",
    "priceAndRisks.georisquesHeading",
    "features[].label",
  ],

  editorial: [
    "headline",
    "eyebrow",
    "excerpt",
    "mainImage.alt",
    "ctas[].title",
    "ctas[].text",
    "sidebarShowcaseItems[].title",
    "sidebarShowcaseItems[].subtitle",
    "sidebarShowcaseItems[].image.alt",
    "relatedReading.eyebrow",
    "relatedReading.title",
    "relatedReading.text",
    "relatedReading.links[].title",
    "relatedReading.links[].linkLabel",
    "sources[].label",
    "sources[].note",
    "seo.metaTitle",
    "seo.metaDescription",
  ],

  propertyIndexPage: [
    "eyebrow",
    "heroTitle",
    "heroText",
    "heroImage.alt",
    "intro",
    "soldHighlightsEyebrow",
    "soldHighlightsTitle",
    "soldHighlights[].image.alt",
    "soldHighlights[].status",
    "soldHighlights[].operationType",
    "soldHighlights[].title",
    "soldHighlights[].propertyType",
    "soldHighlights[].location",
    "soldHighlights[].story",
    "emptyStateTitle",
    "emptyStateText",
    "seo.metaTitle",
    "seo.metaDescription",
  ],

  siteSettings: [
    "navigation[].label",
    "contactRole",
    "contactImage.alt",
  ],

  legalPage: [
    "pageTitle",
    "intro",
    "heroImage.alt",
  ],

  feesPage: [
    "pageTitle",
    "intro",
    "heroImage.alt",
    "rows[].range",
    "rows[].fee",
    "footerNote",
  ],

  editorialIndexPage: [
    "eyebrow",
    "heroTitle",
    "heroText",
    "heroImage.alt",
    "intro",
    "ctaTitle",
    "ctaText",
    "emptyStateTitle",
    "emptyStateText",
    "seo.metaTitle",
    "seo.metaDescription",
  ],

  contactPage: [
    "headline",
    "excerpt",
    "mainImage.alt",
    "sidebarIntroTitle",
    "sidebarIntroItems[]",
    "sidebarBenefitsTitle",
    "sidebarBenefits[].title",
    "sidebarBenefits[].text",
    "seoTitle",
    "seoDescription",
  ],
}