module.exports = {
  property: [
    "marketingTitle",
    "excerpt",
    "listingCard.eyebrow",
    "listingCard.title",
    "listingCard.excerpt",
    "listingCard.ctaLabel",
    "listingCard.statusLabel",
    "heroExcerpt",
    "sidebarBlocks[].eyebrow",
    "sidebarBlocks[].title",
    "sidebarBlocks[].text",
    "sidebarBlocks[].items[]",
    "sidebarBlocks[].caption",
    "sidebarBlocks[].ctaLabel",
    "sidebarBlocks[].image.alt",
    "seo.metaTitle",
    "seo.metaDescription",
    "gallery[].alt",
    "priceAndRisks.priceHeading",
    "priceAndRisks.priceLabel",
    "priceAndRisks.agencyFeesNote",
    "priceAndRisks.georisquesHeading",
    "features[].label",
	"relatedReading.eyebrow",
    "relatedReading.title",
    "relatedReading.text",
  ],

  editorial: [
    "headline",
    "eyebrow",
    "excerpt",
    "mainImage.alt",
    "ctas[].title",
    "ctas[].text",
    "sidebarShowcaseItems[].title",
    "sidebarShowcaseItems[].subtitle",
    "sidebarShowcaseItems[].image.alt",
    "relatedReading.eyebrow",
    "relatedReading.title",
    "relatedReading.text",
    "relatedReading.links[].title",
    "relatedReading.links[].linkLabel",
    "sources[].label",
    "sources[].note",
    "seo.metaTitle",
    "seo.metaDescription",
	"sidebarApproach.eyebrow",
    "sidebarApproach.title",
    "sidebarApproach.text",
  ],

  propertyIndexPage: [
    "eyebrow",
    "heroTitle",
    "heroText",
    "heroImage.alt",
    "intro",
    "soldHighlightsEyebrow",
    "soldHighlightsTitle",
    "soldHighlights[].image.alt",
    "soldHighlights[].status",
    "soldHighlights[].operationType",
    "soldHighlights[].title",
    "soldHighlights[].propertyType",
    "soldHighlights[].location",
    "soldHighlights[].story",
    "emptyStateTitle",
    "emptyStateText",
    "seo.metaTitle",
    "seo.metaDescription",
  ],

  siteSettings: [
    "navigation[].label",
    "contactRole",
    "contactImage.alt",
  ],

  legalPage: [
    "pageTitle",
    "intro",
    "heroImage.alt",
  ],

  feesPage: [
    "pageTitle",
    "intro",
    "heroImage.alt",
    "rows[].range",
    "rows[].fee",
    "footerNote",
  ],

  editorialIndexPage: [
    "eyebrow",
    "heroTitle",
    "heroText",
    "heroImage.alt",
    "intro",
    "ctaTitle",
    "ctaText",
    "emptyStateTitle",
    "emptyStateText",
    "seo.metaTitle",
    "seo.metaDescription",
  ],
  
    personProfile: [
    "eyebrow",
    "headline",
    "excerpt",
    "mainImage.alt",
    "facts[].label",
    "facts[].value",
    "methodTitle",
    "methodItems[]",
    "ctaTitle",
    "ctaText",
    "seoTitle",
    "seoDescription",
  ],
  
    homePage: [
    "hero.eyebrow",
    "hero.title",
    "hero.text",
    "hero.primaryLabel",
    "hero.secondaryLabel",
    "hero.image.alt",

    "content[].eyebrow",
    "content[].title",
    "content[].text",
    "content[].linkLabel",
    "content[].image.alt",

    "seo.metaTitle",
    "seo.metaDescription",
  ],
  
methodPage: [
  "eyebrow",
  "headline",
  "subtitle",
  "excerpt",

  "mainImage.alt",

  "readingTime",

  "sidebarApproach.eyebrow",
  "sidebarApproach.title",
  "sidebarApproach.text",

  "sidebarTitle",
  "sidebarText",
  "sidebarCtaLabel",

  "sidebarShowcaseItems[].title",
  "sidebarShowcaseItems[].subtitle",
  "sidebarShowcaseItems[].image.alt",

  "bottomCtaTitle",
  "bottomCtaText",
  "bottomCtaLabel",

  "seoTitle",
  "seoDescription",
  ],

  contactPage: [
    "headline",
    "excerpt",
    "mainImage.alt",
    "sidebarIntroTitle",
    "sidebarIntroItems[]",
    "sidebarBenefitsTitle",
    "sidebarBenefits[].title",
    "sidebarBenefits[].text",
    "seoTitle",
    "seoDescription",
  ],
}